function Rotx = Rotx(t)
%ROTX
%    ROTX = ROTX(T)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    09-Mar-2021 22:05:28

%This is a function that calculates the 3x3 rotation matrix around the x-axis for input t in radians.
t2 = cos(t);
t3 = sin(t);
Rotx = reshape([1.0,0.0,0.0,0.0,t2,t3,0.0,-t3,t2],[3,3]);
