function Roty = Roty(t)
%ROTY
%    ROTY = ROTY(T)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    09-Mar-2021 22:05:28

%This is a function that calculates the 3x3 rotation matrix around the y-axis for input t in radians.
t2 = cos(t);
t3 = sin(t);
Roty = reshape([t2,0.0,-t3,0.0,1.0,0.0,t3,0.0,t2],[3,3]);
