/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) nonlinearConstr_ ## ID
#endif

#include <math.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

static const casadi_int casadi_s0[69] = {1, 33, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[10] = {33, 2, 0, 3, 5, 10, 21, 32, 10, 21};
static const casadi_int casadi_s4[3] = {33, 0, 0};

/* nonlinearConstr:(Control Points[1x33])->(C[2],Ceq[],dC[33x2,5nz],dCeq[33x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=1.0000000000000000e-003;
  a1=4.8749721171018684e-001;
  a2=arg[0]? arg[0][10] : 0;
  a3=sin(a2);
  a4=arg[0]? arg[0][21] : 0;
  a5=cos(a4);
  a6=(a3*a5);
  a7=cos(a2);
  a8=sin(a4);
  a9=(a7*a8);
  a6=(a6+a9);
  a9=arg[0]? arg[0][32] : 0;
  a10=cos(a9);
  a11=(a6*a10);
  a12=(a7*a5);
  a13=(a3*a8);
  a12=(a12-a13);
  a13=sin(a9);
  a14=(a12*a13);
  a11=(a11+a14);
  a11=(a1*a11);
  a14=4.1780176208274378e-001;
  a15=(a14*a6);
  a16=3.9203155916565541e-001;
  a17=(a16*a3);
  a15=(a15+a17);
  a11=(a11+a15);
  a17=7.7839831977515161e-001;
  a11=(a11-a17);
  a11=(a0*a11);
  if (res[0]!=0) res[0][0]=a11;
  a11=3.2393332849935974e-001;
  a15=(a15-a11);
  a15=(a0*a15);
  if (res[0]!=0) res[0][1]=a15;
  a15=cos(a2);
  a11=(a5*a15);
  a2=sin(a2);
  a17=(a8*a2);
  a11=(a11-a17);
  a17=(a10*a11);
  a5=(a5*a2);
  a8=(a8*a15);
  a5=(a5+a8);
  a5=(a13*a5);
  a17=(a17-a5);
  a17=(a1*a17);
  a11=(a14*a11);
  a16=(a16*a15);
  a11=(a11+a16);
  a17=(a17+a11);
  a17=(a0*a17);
  if (res[2]!=0) res[2][0]=a17;
  a17=cos(a4);
  a16=(a7*a17);
  a4=sin(a4);
  a15=(a3*a4);
  a16=(a16-a15);
  a10=(a10*a16);
  a7=(a7*a4);
  a3=(a3*a17);
  a7=(a7+a3);
  a13=(a13*a7);
  a10=(a10-a13);
  a10=(a1*a10);
  a14=(a14*a16);
  a10=(a10+a14);
  a10=(a0*a10);
  if (res[2]!=0) res[2][1]=a10;
  a10=cos(a9);
  a12=(a12*a10);
  a9=sin(a9);
  a6=(a6*a9);
  a12=(a12-a6);
  a1=(a1*a12);
  a1=(a0*a1);
  if (res[2]!=0) res[2][2]=a1;
  a11=(a0*a11);
  if (res[2]!=0) res[2][3]=a11;
  a0=(a0*a14);
  if (res[2]!=0) res[2][4]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int nonlinearConstr(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int nonlinearConstr_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int nonlinearConstr_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nonlinearConstr_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int nonlinearConstr_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nonlinearConstr_release(int mem) {
}

CASADI_SYMBOL_EXPORT void nonlinearConstr_incref(void) {
}

CASADI_SYMBOL_EXPORT void nonlinearConstr_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nonlinearConstr_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int nonlinearConstr_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real nonlinearConstr_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nonlinearConstr_name_in(casadi_int i){
  switch (i) {
    case 0: return "Control Points";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nonlinearConstr_name_out(casadi_int i){
  switch (i) {
    case 0: return "C";
    case 1: return "Ceq";
    case 2: return "dC";
    case 3: return "dCeq";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nonlinearConstr_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nonlinearConstr_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    case 3: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nonlinearConstr_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_nonlinearConstr(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  casadi_real w[73];
  casadi_int *iw = 0;
  const casadi_real* arg[1] = {0};
  casadi_real* res[4] = {0};
  if (argc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"nonlinearConstr\" failed. Too many input arguments (%d, max 1)", argc);
  if (resc>4) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"nonlinearConstr\" failed. Too many output arguments (%d, max 4)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+40);
  --resc;
  res[0] = w+33;
  if (--resc>=0) res[1] = w+35;
  if (--resc>=0) res[2] = w+35;
  if (--resc>=0) res[3] = w+40;
  i = nonlinearConstr(arg, res, iw, w+40, 0);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"nonlinearConstr\" failed.");
  if (res[0]) resv[0] = casadi_to_mex(casadi_s1, res[0]);
  if (res[1]) resv[1] = casadi_to_mex(casadi_s2, res[1]);
  if (res[2]) resv[2] = casadi_to_mex(casadi_s3, res[2]);
  if (res[3]) resv[3] = casadi_to_mex(casadi_s4, res[3]);
}
#endif


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[16];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    mex_nonlinearConstr(resc, resv, argc, argv);
    return;
  } else if (strcmp(buf, "nonlinearConstr")==0) {
    mex_nonlinearConstr(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'nonlinearConstr'");
}
#endif
#ifdef __cplusplus
} /* extern "C" */
#endif
