function Rotz = Rotz(t)
%ROTZ
%    ROTZ = ROTZ(T)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    09-Mar-2021 22:05:28

%This is a function that calculates the 3x3 rotation matrix around the z-axis for input t in radians.
t2 = cos(t);
t3 = sin(t);
Rotz = reshape([t2,t3,0.0,-t3,t2,0.0,0.0,0.0,1.0],[3,3]);
